# Generated by Django 5.0.1 on 2024-02-16 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_rename_specialiation_employeeexperience_specialization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeQualities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardworking', models.CharField(max_length=200, null=True)),
                ('flexibility', models.CharField(max_length=100, null=True)),
                ('attitude', models.CharField(max_length=50, null=True)),
                ('reliability', models.CharField(max_length=100, null=True)),
                ('attentiontodetail', models.CharField(max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techskills', models.CharField(max_length=200, null=True)),
                ('physskills', models.CharField(max_length=100, null=True)),
                ('timemanagement', models.CharField(max_length=50, null=True)),
                ('communicationskills', models.CharField(max_length=100, null=True)),
                ('customerhandling', models.CharField(max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
