# Generated by Django 5.0.1 on 2024-02-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employeequalities_employeeskills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeskills',
            old_name='techskills',
            new_name='communication_skills',
        ),
        migrations.RemoveField(
            model_name='employeeskills',
            name='communicationskills',
        ),
        migrations.RemoveField(
            model_name='employeeskills',
            name='customerhandling',
        ),
        migrations.RemoveField(
            model_name='employeeskills',
            name='physskills',
        ),
        migrations.RemoveField(
            model_name='employeeskills',
            name='timemanagement',
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='customer_handling_skills',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='physical_skills',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='technical_skills',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='time_management_skills',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
