# Generated by Django 5.0.1 on 2024-03-01 15:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_rename_techskills_employeeskills_communication_skills_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeSkills',
            new_name='EmployeeSkill',
        ),
    ]
