# Generated by Django 5.0.1 on 2024-03-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_rename_employeeskill_employeeexperiences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='multiskilled',
            new_name='communication_skills',
        ),
        migrations.RenameField(
            model_name='employeeexperiences',
            old_name='communication_skills',
            new_name='multiskilled',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='major',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='yearsofexp',
        ),
        migrations.RemoveField(
            model_name='employeeexperiences',
            name='customer_handling_skills',
        ),
        migrations.RemoveField(
            model_name='employeeexperiences',
            name='physical_skills',
        ),
        migrations.RemoveField(
            model_name='employeeexperiences',
            name='technical_skills',
        ),
        migrations.RemoveField(
            model_name='employeeexperiences',
            name='time_management_skills',
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='customer_handling_skills',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='physical_skills',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='technical_skills',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='time_management_skills',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperiences',
            name='comment',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperiences',
            name='major',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperiences',
            name='specialization',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperiences',
            name='yearsofexp',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
