# Generated by Django 5.0.1 on 2024-03-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_rename_communication_skills_employeeexperience_multiskilled_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeQualities',
        ),
    ]
