# Generated by Django 5.0.1 on 2024-03-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_rename_firstname_usersignup_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='dateofbirth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
