# Generated by Django 5.0.1 on 2024-03-31 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_rename_customuser_usersignup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersignup',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='usersignup',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
