# Generated by Django 5.0.1 on 2024-03-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_rename_first_name_usersignup_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
