# Generated by Django 5.0.1 on 2024-03-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_usersignup_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'custom_sessions',
            },
        ),
    ]
