# Generated by Django 5.0.1 on 2024-04-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_alter_employeedetail_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSignup',
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='dateofbirth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='firstname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='lastname',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='uemail',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='upassword',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='usercontact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='usergender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
