# Generated by Django 5.0.1 on 2024-04-07 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_employeedetail_email_employeedetail_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='password',
        ),
    ]
