# Generated by Django 5.0.1 on 2024-04-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0029_remove_employeedetail_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='dateofbirth',
            field=models.DateField(null=True),
        ),
    ]
